apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-block
provisioner: gluster.org/glusterblock
parameters:
  resturl: "http://10.43.35.193:8081"
  restauthenabled: "false"
  hacount: "3"
