# HEADER: This file was autogenerated at 2018-07-07 15:23:59 +0800
# HEADER: by puppet.  While it can still be managed manually, it
# HEADER: is definitely not recommended.
define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-10.compute.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.elasticsearch-nodes.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-10.nova-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.keystone-admin-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.neutron-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.cinder-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-14.storage.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-16.nova-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-16.compute.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.glance-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.heat-cfn-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-13.storage.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-12.compute.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-16.libvirt-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.rabbitmq-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.controller.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.glance-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-13.storage.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.heat-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-neutron-control-plane
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-horizon
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-keystone
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.ceph-mon-cluster.capacity
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.heat-cloudwatch-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-16.compute.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-mysql
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.nova-metadata-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-16.compute.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.nova-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.horizon-https.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.controller.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.nova-metadata-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.apache.worker
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-17.compute.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.pacemaker-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-17.compute.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-12.compute.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.ceph-mon-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.glance-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-5.storage.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-11.libvirt-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-6.storage.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.rabbitmq-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.nova-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-influxdb
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-14.storage.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.nova-novncproxy-websocket.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-9.nova-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-8.compute.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.heat-cfn-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-12.compute.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.nova-metadata-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-haproxy-openstack
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.cinder-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.controller.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-pacemaker
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-ceilometer
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-10.compute.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.heat-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-15.compute.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.rabbitmq-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.cinder-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-memcached
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.neutron-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-9.compute.nova-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.heat-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.neutron-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-12.compute.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.horizon-https.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-5.storage.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-cinder-control-plane
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.elasticsearch-nodes.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.neutron-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.neutron-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.influxdb-nodes.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.mysql.node-status
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-11.compute.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-9.compute.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-6.ceph-osd-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.controller.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-10.libvirt-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.haproxy-openstack.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-10.compute.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.neutron-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-rabbitmq
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-17.compute.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-17.compute.nova-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.heat-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-9.compute.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.heat-cloudwatch-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.influxdb-nodes.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.mysqld-tcp.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.keystone-public-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-13.storage.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-12.nova-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.horizon-https.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-neutron-data-plane
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-12.compute.nova-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.pacemaker-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-13.storage.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.keystone-public-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.keystone-public-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.keystone-response-time.duration
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-5.storage.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.apache.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-6.storage.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.controller.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.glance-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-9.compute.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.haproxy-openstack.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-15.compute.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.heat-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.mysqld-tcp.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.nova-instances.creation-time
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-11.compute.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.controller.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.rabbitmq-cluster.disk
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.controller.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.influxdb-nodes.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.influxdb-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.controller.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-15.compute.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.nova-novncproxy-websocket.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-nodes-controller
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.keystone-admin-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-12.compute.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.horizon-https.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.ceph-mon-cluster.capacity
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.controller.log-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.glance-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-13.storage.osd-disk
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-cinder-scheduler
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-rabbitmq-service
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-logs-compute
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-keystone-response-time
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-keystone-admin-api
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-neutron-metadata
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-keystone-public-api
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-neutron-l3
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-mysql
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-cinder-logs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-memcached-service
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-api-check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-ceph-mon-service
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-free-vcpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-heat-logs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-keystone-public-api-check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-free-memory
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-neutron-openvswitch
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-heat-cfn-api-check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-heat-cfn-api
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-cinder-v2-api-check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-neutron-api
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-keystone-public-api-endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-haproxy-openstack
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-heat-api
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-logs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-neutron-logs-compute
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-glance-registry-api
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-compute
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-mysqld-tcp
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-glance-logs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-elasticsearch-service
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-cinder-api
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-cert
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-apache
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-instances
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-heat-cfn-api-endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-ceilometer-api
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.cinder-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-9.libvirt-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.nova-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.heat-cfn-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-10.compute.nova-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-ceph
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.controller.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-11.compute.nova-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-5.storage.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.ceph-mon-cluster.health
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-novncproxy-websocket
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.heat-cloudwatch-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-17.neutron-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-nodes-influxdb-nodes
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-11.compute.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-elasticsearch
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-glance-api-endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.glance-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.elasticsearch-nodes.data-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.keystone-admin-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-nodes-compute
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-6.storage.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.heat-cfn-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-9.compute.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.glance-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.horizon-https.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-pacemaker-service
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.nova-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.rabbitmq-cluster.queue
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.pacemaker-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-10.compute.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-rabbitmq-cluster
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.mysql.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-glance
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-libvirt-service
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-ceilometer-api-check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.controller.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.nova-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.mysql.node-status
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-15.compute.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-17.compute.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.glance-registry-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.keystone-response-time.duration
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.haproxy-openstack.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.mysql-nodes.mysql-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.neutron-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-nodes-mysql-nodes
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-11.compute.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.neutron-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-heat-api-check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-neutron-dhcp
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-16.compute.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-5.storage.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.nova-instances.creation-time
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.heat-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-nodes-elasticsearch-nodes
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-nova-control-plane
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-9.neutron-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.keystone-public-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-5.ceph-osd-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.keystone-admin-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.rabbitmq-cluster.memory
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.elasticsearch-nodes.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.mysqld-tcp.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-14.storage.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.heat-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.glance-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.ceph-mon-cluster.capacity
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-17.nova-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.controller.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.nova-novncproxy-websocket.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-glance-api
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.controller.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.cinder-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-neutron-api-check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-11.compute.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.nova-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.heat-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.rabbitmq-cluster.memory
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-16.neutron-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-10.neutron-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.cinder-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.mysql-nodes.mysql-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.horizon-https.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-10.compute.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.keystone-public-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.cinder-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-15.compute.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.ceph-mon-cluster.health
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.apache.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-nova-data-plane
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.apache.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-ceph-mon-cluster
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-conductor
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.elasticsearch-nodes.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.controller.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.keystone-public-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.elasticsearch-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.elasticsearch-cluster.health
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.nova-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-5.storage.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.keystone-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.influxdb-nodes.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.rabbitmq-cluster.disk
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-15.libvirt-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.ceph-mon-cluster.health
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-11.neutron-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-consoleauth
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.cinder-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-12.neutron-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.controller.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-api
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-14.storage.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.heat-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-cinder-volume
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-nodes-storage
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-5.storage.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-16.compute.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-heat-api-endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.cinder-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.controller.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-17.compute.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-8.compute.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.nova-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-6.storage.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-keystone-logs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-5.storage.osd-disk
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.influxdb-nodes.data-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-15.compute.nova-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-neutron-api-endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-17.libvirt-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-12.compute.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.controller.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.heat-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-16.compute.nova-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.mysql.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.mysql.node-status
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.neutron-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-14.ceph-osd-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-15.nova-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-6.storage.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.glance-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-14.storage.osd-disk
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.controller.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-11.compute.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-15.neutron-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.controller.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-api-endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.cinder-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-9.compute.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.mysql-nodes.mysql-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.apache.worker
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.neutron-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-14.storage.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-8.neutron-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-cinder-api-endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-13.storage.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.mysql.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.nova-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.elasticsearch-nodes.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.neutron-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.cinder-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-16.compute.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.neutron-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-14.storage.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-ceph-osd-service
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.keystone-admin-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.glance-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-11.nova-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-influxdb-api-check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-apache
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-16.compute.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-8.compute.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-9.compute.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.glance-registry-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-6.storage.osd-disk
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.controller.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.keystone-admin-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-15.compute.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.keystone-response-time.duration
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.controller.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-glance-api-check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-12.compute.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-10.compute.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.ceph-mon-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.keystone-public-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.keystone-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-15.compute.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-influxdb-service
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-8.compute.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.keystone-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.apache.worker
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-8.libvirt-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-6.storage.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-8.compute.nova-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-horizon-https
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.glance-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-8.compute.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.elasticsearch-nodes.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-9.compute.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.ceph-mon-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-metadata-api
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-6.storage.root-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.memcached-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.rabbitmq-cluster.memory
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-12.libvirt-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.controller.log-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-8.nova-logs-compute.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.rabbitmq-cluster.queue
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.memcached-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-11.compute.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-global-heat
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.nova-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.controller.log-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.controller.other-fs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.keystone-public-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.keystone-public-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-heat-cloudwatch-api
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.rabbitmq-cluster.queue
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.memcached-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-8.compute.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-17.compute.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-13.storage.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.influxdb-nodes.swap
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.glance-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.rabbitmq-cluster.disk
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-7.influxdb-nodes.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-nova-scheduler
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.nova-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.nova-api-endpoint.endpoint
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-13.storage.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-10.compute.network-tx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-elasticsearch-cluster
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.glance-registry-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.heat-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-neutron-logs
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.heat-cfn-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-3.heat-logs.error
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-8.compute.cpu
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-1.cinder-api.http_errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-14.storage.network-rx
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-17.compute.hdd-errors
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-13.ceph-osd-service.check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-services-cinder-api-check
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.heat-cfn-api.backends
}

define command {
	command_line                   /usr/lib/nagios/plugins/check_dummy 3 'No data received for at least 130 seconds'
	command_name                   return-unknown-node-2.nova-instances.creation-time
}
