apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 10.67.36.57
  ports:
  - port: 1
- addresses:
  - ip: 10.67.36.56
  ports:
  - port: 1
- addresses:
  - ip: 10.67.36.55
  ports:
  - port: 1
- addresses:
  - ip: 10.67.36.54
  ports:
  - port: 1
