apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: logstash
  namespace: default
  labels:
    app: logstash
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: logstash
        image: logstash:6.8.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9600
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/logstash/pipeline
          name: vol2
        - mountPath: /usr/share/logstash/config
          name: vol1
      volumes:
      - configMap:
          defaultMode: 256
          name: logstash-pipeline-conf
          optional: false
        name: vol2
      - configMap:
          defaultMode: 256
          name: logstash-conf
          optional: false
        name: vol1


