groups:
- name: redis
  rules:

  - alert: RedisDown
    expr: redis_up == 0
    for: 1m
    labels:
      severity: critical
      type: service
      environment: "production"
    annotations:
      summary: Redis down (instance {{ $labels.instance }})
      description: "Redis instance is down\n VALUE = {{ $value }}\n LABELS= {{ $labels }}"

  - alert: RedisOutOfConfiguredMaxmemory
    expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
    for: 2m
    labels:
      severity: warning
      type: service
      environment: "production"
    annotations:
      summary: Redis out of configured maxmemory (instance {{ $labels.instance }})
      description: "Redis is running out of configured maxmemory (> 90%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: RedisTooManyConnections
    expr: redis_connected_clients > 100
    for: 2m
    labels:
      severity: warning
      type: service
      environment: "production"
    annotations:
      summary: Redis too many connections (instance {{ $labels.instance }})
      description: "Redis instance has too many connections\n VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
