version: "3.7"

networks:
  alertsnitch:
    driver: bridge
services:
  postgresql-server:
    restart: always
    image: 'bitnami/postgresql:latest'
    container_name: mydb
    volumes:
      - alertsnitch-db:/bitnami/postgresql
      - ./postgres/0.0.1-bootstrap.sql:/docker-entrypoint-initdb.d/0.0.1-bootstrap.sql
      - ./postgres/0.1.0-fingerprint.sql:/docker-entrypoint-initdb.d/0.1.0-fingerprint.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_PASSWORD=Foxconn123
    networks:
      - alertsnitch

  alertsnitch:
    image: 'registry.gitlab.com/yakshaving.art/alertsnitch:latest'
    environment:
      ALERTSNITCH_DSN: user=postgres password=Foxconn123 host=mydb dbname=postgres sslmode=disable
      ALERTSNITCH_BACKEND: postgres
    ports:
      - 9567:9567
    networks:
      - alertsnitch
    depends_on:
      - postgresql-server
volumes:
  alertsnitch-db:    
