apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: zabbix-server-mysql
  namespace: default
  labels:
    app: zabbix-server-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server-mysql
  template:
    metadata:
      labels:
        app: zabbix-server-mysql
    spec:
      securityContext:
        fsGroup: 1000
        sysctls:
        - name: net.ipv4.ip_local_port_range
          value: "1024 65000"
      containers:
      - name: zabbix-server-mysql
        image: zabbix/zabbix-server-mysql:centos-4.4.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mailsender
          mountPath: /usr/lib/zabbix/alertscripts
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: ZBX_SERVER_NAME
          value: "zabbixserver"
        - name: ZAB_CACHESIZE
          value: "1024M"
        - name: ZBX_JAVAGATEWAY_ENABLE
          value: "true"
        - name: DB_SERVER_HOST
          value: "maxscale"
        - name: MYSQL_DATABASE
          value: "zabbix"
        - name: MYSQL_USER
          value: "zabbix"
        - name: MYSQL_PASSWORD
          value: "vSTJ456"
        - name: MYSQL_ROOT_PASSWORD
          value: "vSTJ456"
        - name: ZBX_JAVAGATEWAY
          value: "zabbix-java-gateway"
        - name: ZBX_STARTPOLLERS
          value: "10"
        - name: ZBX_STARTPOLLERSUNREACHABLE
          value: "10"
        - name: ZBX_STARTPINGERS
          value: "50"
        - name: ZBX_STARTDISCOVERERS
          value: "10"
        - name: ZBX_STARTHTTPPOLLERS
          value: "100"
        - name: ZBX_STARTTRAPPERS
          value: "100"
        - name: ZBX_STARTJAVAPOLLERS
          value: "10"
        - name: ZBX_VALUECACHESIZE
          value: "16M"
        - name: ZBX_STARTDBSYNCERS
          value: "8"
        ports:
        - containerPort: 10051
          protocol: TCP
      - name: zabbix-agent
        image: zabbix/zabbix-agent:centos-4.4.0
        imagePullPolicy: IfNotPresent
        env:
        - name: ZBX_SERVER_HOST
          value: "zabbix-server-mysql,127.0.0.1"
        - name: ZBX_HOSTNAME
          value: "Zabbix server"
        resources:
          limits:
            cpu: "4"
            memory: 12Gi
          requests:
            cpu: "4"
            memory: 12Gi
      volumes:
        - name: mailsender
          configMap:
            name: mcmailsender
            defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server-mysql
  labels:
    app: zabbix-server-mysql
spec:
  selector:
    app: zabbix-server-mysql
  ports:
  - protocol: TCP
    port: 10051
    nodePort: 30051
  type: NodePort
