---

- name: copy lld-disks.py for trusty centos6 and centos7
  copy:
    src: lld-disks.py
    dest: /usr/local/bin/lld-disks.py
    mode: '0755'
  when: ansible_distribution_major_version == "14" or ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"

- name: copy lld-disks.py for xenial
  copy:
    src: lld-disks-3.py
    dest: /usr/local/bin/lld-disks.py
    mode: '0755'
  when: ansible_distribution_major_version == "16"

- name: add zabbix repo for trusty
  apt_repository:
    repo: deb [arch=amd64] http://10.67.51.164/zabbix3.2 trusty main
    filename: zabbix3.2
    state: present
  when: ansible_distribution_major_version == "14"

- name: add zabbix repo for xenial
  apt_repository:
    repo: deb [arch=amd64] http://10.67.51.164/zabbix3.2 xenial main
    filename: zabbix3.2
    state: present
  when: ansible_distribution_major_version == "16"

- name: add zabbix key for ubuntu
  apt_key:
    id: A14FE591
    url: http://10.67.51.164/aptkey/082AB56BA14FE591
    state: present
  when: ansible_distribution_major_version == "14" or ansible_distribution_major_version == "16"

- name: install zabbix-agent and zabbix-sender package for ubuntu
  apt: name={{ item }} update_cache=yes
  with_items:
  - zabbix-agent
  - zabbix-sender
  when: ansible_pkg_mgr == "apt"

- name: install zabbix-agent and zabbix-sender package for centos
  yum: name={{ item }} update_cache=yes
  with_items:
  - zabbix-agent
  - zabbix-sender
  when: ansible_pkg_mgr == "yum"

- name: enable zabbix-agent service
  service: name=zabbix-agent enabled=yes

- name: copy pageinout.sh userparameter_diskstats.conf
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  with_items:
  - { src: 'pageinout.sh',dest: '/etc/zabbix/zabbix_agentd.d',mode: '0755' }
  - { src: 'userparameter_diskstats.conf',dest: '/etc/zabbix/zabbix_agentd.d',mode: '0644' }

- name: setup cron for trapper
  cron:
    name: "zabbix trapper"
    user: root
    minute: "*/1"
    job: "/etc/zabbix/zabbix_agentd.d/pageinout.sh"

- name: configure zabbix agent 
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify:
  - restart zabbix agent
