version: "3.3"

services:
  repo:
    image: nginx:alpine
    configs:
      - source: nginx_default
        target: /etc/nginx/conf.d/default.conf
    ports:
    - 80:80
    deploy:
      replicas: 2
configs:
  nginx_default:
    file: ./default.conf
