version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    user: "0"
    volumes:
      - ~/prometheus-grafana/prometheus:/etc/prometheus
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ~/prometheus-grafana/alertmanager/alertmanager.yml:/etc/prometheus/alertmanager.yml
      - alertmanager:/data
    command:
      - '--config.file=/etc/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093
    links:
      - prometheus
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ~/prometheus-grafana/grafana/provisioning:/etc/grafana/provisioning
      - /opt/grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100
volumes:
  prometheus: 
  alertmanager:
