---
- name: provisioning containers on lxd
  hosts: lxd
  vars:
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
    servers:
      - name: mydb01
        meta:
          group1: pgmaster
          group2: mydb
      - name: mydb02
        meta:
          group1: pgslave
          group2: mydb

  roles:
    - provision_container

- name: deploy postgresql-14 on CentOS 7
  hosts: pgmaster:pgslave
  roles:
    - initial_vm
    - initial_pg

- name: initial master
  hosts: pgmaster
  roles:
    - initial_master

- name: initial slave
  hosts: pgslave

  roles:
    - initial_slave

