apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: logstash
  namespace: default
  labels:
    app: logstash
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: logstash
        image: logstash:6.8.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
        ports:
        - containerPort: 9600
          protocol: TCP
        resources:
          limits:
            cpu: "8"
            memory: 16Gi
          requests:
            cpu: "8"
            memory: 16Gi
        volumeMounts:
        - mountPath: /usr/share/logstash/pipeline
          name: vol2
        - mountPath: /usr/share/logstash/config
          name: vol1
      volumes:
      - configMap:
          defaultMode: 256
          name: logstash-pipeline-conf
          optional: false
        name: vol2
      - configMap:
          defaultMode: 256
          name: logstash-conf
          optional: false
        name: vol1


