version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    user: "0"
    volumes:
      - ~/promsrv/prometheus:/etc/prometheus
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=490GB'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ~/promsrv/alertmanager/alertmanager.yml:/etc/prometheus/alertmanager.yml
      - alertmanager:/data
    command:
      - '--config.file=/etc/prometheus/alertmanager.yml'
      - '--storage.path=/data'
      - '--web.listen-address=0.0.0.0:9082'
    ports:
      - 9093:9093
      - 9082:9082
    links:
      - prometheus
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ~/promsrv/grafana/provisioning:/etc/grafana/provisioning
      - ~/promsrv/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - 'GF_PATHS_CONFIG=/etc/grafana/grafana.ini'
    links:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100
volumes:
  prometheus: 
  alertmanager:
  grafana:
