apiVersion: v1
kind: Endpoints
metadata:
 name: glusterfs41
subsets:
 - addresses:
   - ip: 10.67.36.151
   ports:
   - port: 1
     protocol: TCP
 - addresses:
   - ip: 10.67.36.152
   ports:
   - port: 1
     protocol: TCP
 - addresses:
   - ip: 10.67.36.153
   ports:
   - port: 1
     protocol: TCP
