kind: Service
apiVersion: v1
metadata:
  labels:
    app: heketi
  name: heketi
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: heketi
